name: Create matrix
description: Create matrix
inputs:
  matrixstr:
    description: 'input yaml matrix as multiline string'
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        # FIXME: input sanity check to prevent shell injection
        python3 $GITHUB_ACTION_PATH/matrix_yaml_to_json.py << EOF
        ${{ inputs.matrixstr }}
        EOF
      shell: bash
