name: Create matrix
description: Create matrix
inputs:
  matrixstr:
    description: 'input yaml matrix as multiline string'
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        printenv
        pwd
        ls -lR

        # FIXME: input sanity check to prevent shell injection
        python3 matrix_yaml_to_json.py
      shell: sh
